# Generated by Django 3.2.8 on 2021-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='key_words',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
